### ISSUE TITLE
Add other PHP version supports

### ISSUE THREAD

**Issue by peter279k** [CircleCI-Public/cimg-php#1]
As title, it seems that this repository misses the `php-7.0` and `php-7.1` versions.

IMHO, I think we can consider adding these missing PHP version supports.

Once this issue is accepted, I can work on this and please add `#orbtoberfest` on this issue because of the [hacktoberfest circleci](https://hacktoberfest.circleci.com) :).

**Comment by felicianotech** [comment]
Those versions are too old for this repo. They won't be added.

**Comment by om4csaba** [comment]
Hi,

Can you revisit this decision? For example, PHP 5.6 is available in this repo, but 7.0 and 7.1 are not. 
I made quick test builds, and everything worked. Would be useful if users will not be forced to use mixed source. Currently, our config look like this:

```yaml
- image: circleci/php:7.0-cli
- image: circleci/php:7.1-cli
- image: cimg/php:7.2
- image: cimg/php:7.3
- image: cimg/php:7.4
- image: cimg/php:8.0
```  

Thanks
