### ISSUE TITLE
 sudo: docker-php-ext-install: command not found

### ISSUE THREAD

**Issue by shoosah** [CircleCI-Public/cimg-php#125]
Here is part of my config.yml:
```
version: 2
jobs:
  build:
    working_directory: ~/platform

    docker:
      - image: cimg/php:8.0-browsers
        auth:
          username: publictrust
          password: ${DOCKERHUB_PASSWORD}

    steps:

      - checkout:
          path: ~/platform

      # Setup the environment variables
      - run: cd ./project && cp .env.example .env

      # Testing dependencies
      - run: sudo apt update && sudo apt install zlib1g-dev sqlite3 libsqlite3-dev libpng-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install pcntl
      - run: sudo docker-php-ext-install gd
      - run: sudo composer self-update
```
However, it fails with the following:
sudo: docker-php-ext-install: command not found

So I updated the following:
```
      - run: sudo apt update && sudo apt install zlib1g-dev sqlite3 libsqlite3-dev libpng-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install pcntl
      - run: sudo docker-php-ext-install gd
      - run: sudo composer self-update
```
into the following:
```
      - run: sudo apt update && sudo apt install sqlite3 libsqlite3-dev libpng-dev libzip-dev php-zip php-gd php-sqlite3
      - run: sudo composer self-update
```
And my tests are running now. I wonder if this is the right replacement?
