### ISSUE TITLE
Document the suggest way to add additional extensions during a build

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-php#132]
This is for this repo's readme, but we might want to take a look at the orb as well.

**Comment by tomjn** [comment]
Noting that refactors in this repo introduced major breakage in any CI pipeline that relied on additional extensions with no warning that it would happen and no notice that it happened unless you dug through the pull requests.

For reference, in my own case we were already using the recommended PECL installation method yet it does not work for unknown reasons

**Comment by felicianotech** [comment]
This is why only unpublished images (by the beginning of this work) were published to these changes. Trying to limit the impact as much as possible.

> For reference, in my own case we were already using the recommended PECL installation method yet it no longer works for unknown reasons

Could you please elaborate? What were you trying to do? What's the error? This Issue should be closed now as I've added the information in the readme but I would love to know if something is missed.

**Comment by tomjn** [comment]
I'm not sure it would be especially useful, our config adds this:

```yaml
            - run:
                name: "Install PHP Runkit 7"
                command: |
                    sudo pecl install runkit7-alpha
                    echo "extension = runkit7.so" | sudo tee --append /etc/php/7.4/cli/conf.d/runkit7.ini
```

Though our test suite was then failing from missing functions from runkit7, I worked around it by specifying the tests require that extension though so PHPUnit trundles along ok now
