### ISSUE TITLE
/usr/local/bin/docker-php-ext-install: line 19: cd: /usr/src/php/ext: No such file or directory for php 8.0 and higher

### ISSUE THREAD

**Issue by r4m-oleksii** [CircleCI-Public/cimg-php#190]
The typical pipeline looks like this
```yml
  build:
    docker:
      - image: cimg/php:7.4.30-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update composer
          command: sudo composer self-update --no-interaction
      - run:
          name: PECL extensions
          command: |
            sudo apt-get update -y && sudo apt-get install -y libpng-dev libmagickwand-dev libmagickwand-6.q16-6
            sudo pecl channel-update pecl.php.net
            sudo bash -c "yes '' | sudo pecl install imagick xdebug || true"
            sudo docker-php-ext-enable imagick
            sudo pecl install pcov
            sudo docker-php-ext-enable pcov
      - run:
          name: Install and enable PHP extensions
          command: | 
            sudo docker-php-ext-install pdo_mysql
            sudo docker-php-ext-enable xdebug
            sudo docker-php-ext-install bcmath
            sudo docker-php-ext-configure gd --enable-gd --prefix=/usr --with-freetype --with-jpeg
            sudo docker-php-ext-install -j$(nproc) gd
```
and it works fine without any troubles. But lately I needed to use a more up to date version of php so I changed the line
```yml
    - image: cimg/php:8.1.12-browsers
```
run the pipeline and got an error
<img width="1220" alt="Снимок экрана 2022-10-31 в 18 04 15" src="https://user-images.githubusercontent.com/108271392/199066464-2f161cdb-64f2-4c36-8034-4a49d12e6086.png">

My short research led me to the script [`docker-php-source`](https://github.com/CircleCI-Public/cimg-php/blob/main/docker-php-scripts/docker-php-source). Truth in that I'm trying to install extensions which already has been installed in basic image, and this bring me to this issue. But with `cimg/php:7.4.30-browsers` everything was fine - how is this possible?
My further research shows me the difference between the behavior of php 7.4 and later versions of php. If I try to install extension which is already installed - this wouldn't dispatch any error. But we will got a warning in some php outputs like result of `php -v`
<img width="536" alt="Снимок экрана 2022-10-31 в 18 24 35" src="https://user-images.githubusercontent.com/108271392/199070457-3c769f23-da47-41b0-b18c-7746285a282b.png">
<img width="551" alt="Снимок экрана 2022-10-31 в 19 05 01" src="https://user-images.githubusercontent.com/108271392/199078184-235b5b16-5de4-4d54-869d-748786ef9ed1.png">
Difference between this outputs is the key because this output is used for defining url to download php distributive in [`docker-php-source` script](https://github.com/CircleCI-Public/cimg-php/blob/main/docker-php-scripts/docker-php-source#L18) which is used in ['docker-php-ext-install'](https://github.com/CircleCI-Public/cimg-php/blob/main/docker-php-scripts/docker-php-ext-install#L14). If we try to do this manually we will get same issue with php 8.1.12 and won't get in 7.4.30
<img width="792" alt="Снимок экрана 2022-10-31 в 19 13 10" src="https://user-images.githubusercontent.com/108271392/199080188-3ac4d279-767f-4355-b06a-72582255e535.png">
<img width="803" alt="Снимок экрана 2022-10-31 в 19 14 44" src="https://user-images.githubusercontent.com/108271392/199080205-708ed258-90f0-4410-893d-a02a22f4b7ca.png">

So I tried to fix this by changing PHP_VER definition from [used one](https://github.com/CircleCI-Public/cimg-php/blob/main/docker-php-scripts/docker-php-source#L17) to more appropriate
```bash
PHP_VER=$(php -v | xargs | awk -F 'PHP ' '{print $2}' | awk '{print $1}')
```
I tested this by rebuilding the images and repeating these steps manually and everything is fine, so I want to discuss this and maybe find a more elegant solution. I know the most elegant and proper way is not to install extensions that are already installed, but in real world it is not always possible to study all the sources unfortunately.
